# ==============================================================================# IOTEC MISSION CONTROL# 015_API_SERVER.py# ==============================================================================from flask import Flask, jsonifyimport sqlite3from pathlib import PathROOT = Path(__file__).resolve().parentDB = ROOT / "MISSION_CONTROL" / "database" / "mission_control.db"app = Flask(__name__)def db():    conn = sqlite3.connect(DB, timeout=30)    conn.row_factory = sqlite3.Row    return conn@app.get("/")def home():    return jsonify({        "system":"IOTEC Mission Control",        "status":"ONLINE",        "version":"1.0.0"    })@app.get("/api/status")def status():    conn = db()    cur = conn.cursor()

cur.execute("PRAGMA journal_mode=WAL")
cur.execute("PRAGMA synchronous=NORMAL")
cur.execute("PRAGMA busy_timeout=30000")    cur.execute("SELECT COUNT(*) total FROM missions")    missions = cur.fetchone()["total"]    cur.execute("SELECT COUNT(*) total FROM system_logs")    logs = cur.fetchone()["total"]    cur.execute("SELECT COUNT(*) total FROM maestro_history")    maestro = cur.fetchone()["total"]    conn.close()    return jsonify({        "status":"ONLINE",        "missions":missions,        "logs":logs,        "maestro":maestro    })@app.get("/api/missions")def missions():    conn = db()    cur = conn.cursor()

cur.execute("PRAGMA journal_mode=WAL")
cur.execute("PRAGMA synchronous=NORMAL")
cur.execute("PRAGMA busy_timeout=30000")    cur.execute("""        SELECT *        FROM missions        ORDER BY id DESC    """)    rows=[dict(x) for x in cur.fetchall()]    conn.close()    return jsonify(rows)@app.get("/api/logs")def logs():    conn=db()    cur=conn.cursor()    cur.execute("""        SELECT *        FROM system_logs        ORDER BY id DESC        LIMIT 100    """)    rows=[dict(x) for x in cur.fetchall()]    conn.close()    return jsonify(rows)@app.get("/api/services")def services():    conn=db()    cur=conn.cursor()    cur.execute("""        SELECT *        FROM api_routes        ORDER BY endpoint    """)    rows=[dict(x) for x in cur.fetchall()]    conn.close()    return jsonify(rows)if __name__=="__main__":    print("="*80)    print("MISSION CONTROL API")    print("="*80)    print("http://127.0.0.1:5000")    print("="*80)    app.run(        host="0.0.0.0",        port=5000,        debug=False    )

