/*
 JavaScript tracking client

 @source https://github.com/piwik/piwik/blob/master/js/piwik.js
 @license https://opensource.org/licenses/BSD-3-Clause BSD-3 Clause (also in js/LICENSE.txt)
 @license magnet:?xt=urn:btih:c80d50af7d3db9be66a4d0a86db0286e4fd33292&dn=bsd-3-clause.txt BSD-3-Clause
*/
(function(){function O(a){"@babel/helpers - typeof";return O="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(c){return typeof c}:function(c){return c&&"function"==typeof Symbol&&c.constructor===Symbol&&c!==Symbol.prototype?"symbol":typeof c},O(a)}function G(){console.error.apply(console,arguments)}function hd(){console.warn.apply(console,arguments)}function id(){if(gc)return Ya.exports;gc=1;(function(a,c){(function(e,g){a.exports=g()})(jd,function(){function e(r){return r.charAt(0).toUpperCase()+
r.substring(1)}function g(r){return function(){return this[r]}}function h(r){if(r)for(var t=0;t<v.length;t++)if(void 0!==r[v[t]])this["set"+e(v[t])](r[v[t]])}var p=["isConstructor","isEval","isNative","isToplevel"],n=["columnNumber","lineNumber"],q=["fileName","functionName","source"],v=p.concat(n,q,["args"],["evalOrigin"]);h.prototype={getArgs:function(){return this.args},setArgs:function(r){if("[object Array]"!==Object.prototype.toString.call(r))throw new TypeError("Args must be an Array");this.args=
r},getEvalOrigin:function(){return this.evalOrigin},setEvalOrigin:function(r){if(r instanceof h)this.evalOrigin=r;else if(r instanceof Object)this.evalOrigin=new h(r);else throw new TypeError("Eval Origin must be an Object or StackFrame");},toString:function(){var r=this.getFileName()||"",t=this.getLineNumber()||"",F=this.getColumnNumber()||"",K=this.getFunctionName()||"";return this.getIsEval()?r?"[eval] ("+r+":"+t+":"+F+")":"[eval]:"+t+":"+F:K?K+" ("+r+":"+t+":"+F+")":r+":"+t+":"+F}};h.fromString=
function(r){var t=r.indexOf("("),F=r.lastIndexOf(")"),K=r.substring(0,t);t=r.substring(t+1,F).split(",");r=r.substring(F+1);if(0===r.indexOf("@")){var J=/@(.+?)(?::(\d+))?(?::(\d+))?$/.exec(r,""),U=J[1],H=J[2];J=J[3]}return new h({functionName:K,args:t||void 0,fileName:U,lineNumber:H||void 0,columnNumber:J||void 0})};for(var w=0;w<p.length;w++)h.prototype["get"+e(p[w])]=g(p[w]),h.prototype["set"+e(p[w])]=function(r){return function(t){this[r]=!!t}}(p[w]);for(p=0;p<n.length;p++)h.prototype["get"+e(n[p])]=
g(n[p]),h.prototype["set"+e(n[p])]=function(r){return function(t){if(isNaN(parseFloat(t))||!isFinite(t))throw new TypeError(r+" must be a Number");this[r]=Number(t)}}(n[p]);for(n=0;n<q.length;n++)h.prototype["get"+e(q[n])]=g(q[n]),h.prototype["set"+e(q[n])]=function(r){return function(t){this[r]=String(t)}}(q[n]);return h})})(Ya);return Ya.exports}function Ma(a){var c=/^(?:(?:https?|ftp):)\/*(?:[^@?]+@)?([^:/#]+)/.exec(a);return c?c[1]:a}function hc(a){var c=document.createElement("a");c.href=a;return{href:c.href,
hostname:c.hostname,pathname:c.pathname}}function ic(a,c){a=String(a);if(-1===a.indexOf("?"+c+"=")&&-1===a.indexOf("&"+c+"="))return a;var e=a.indexOf("?");if(-1===e)return a;var g=a.substr(e+1);e=a.substr(0,e);if(g){var h="",p=g.indexOf("#");-1!==p&&(h=g.substr(p+1),g=g.substr(0,p));p=g.split("&");for(var n=p.length-1;0<=n;n--)g=p[n].split("=")[0],g===c&&p.splice(n,1);(g=p.join("&"))&&(e=e+"?"+g);h&&(e+="#"+h)}return e}function jc(a){return(a=/^([a-z]+):/.exec(a))?a[1]:null}function tb(a,c){a=String(a).toLowerCase();
c=String(c).toLowerCase();if(a===c)return!0;if("."===c.slice(0,1)){if(a===c.slice(1))return!0;var e=a.length-c.length;if(0<e&&a.slice(e)===c)return!0}return!1}function Za(a,c){var e=document.createElement("a");0!==a.indexOf("//")&&0!==a.indexOf("http")&&(0===a.indexOf("*")&&(a=a.substr(1)),0===a.indexOf(".")&&(a=a.substr(1)),a="http://"+a);e.href=c.toAbsoluteUrl(a);return e.pathname?e.pathname:""}function $a(a,c){return c&&a?0===String(a).indexOf(c):!1}function ub(a,c){var e=(new RegExp("[\\?&#]"+
c+"=([^&#]*)")).exec(a);return e?decodeURIComponent(e[1]):""}function ab(a,c){a=ic(a,c.visitorIdUrlParameter);return c.discardHashTag?a.replace(/#.*/,""):a}function x(a){return"undefined"!==typeof a}function xa(a){return"function"===typeof a}function Na(a){return"object"===O(a)}function P(a){return"string"===typeof a||a instanceof String}function qa(a){return"number"===typeof a||P(a)&&!isNaN(a)&&""!==a}function Oa(a){var c=a.length;"."===a.charAt(--c)&&(a=a.slice(0,c));"*."===a.slice(0,2)&&(a=a.slice(1));
-1!==a.indexOf("/")&&(a=a.substr(0,a.indexOf("/")));return a}function kd(a,c,e){a||(a="");c||(c="");if("translate.googleusercontent.com"===a)""===e&&(e=c),c=ub(c,"u"),a=Ma(c);else if("cc.bingj.com"===a||"webcache.googleusercontent.com"===a||"74.6."===a.slice(0,5))c=document.links[0].href,a=Ma(c);return[a,c,e]}function Z(a,c){if(a&&a.indexOf)return a.indexOf(c);if(!x(a)||null===a||0===a.length)return-1;for(var e=0;e<a.length;){if(a[e]===c)return e;e++}return-1}function kc(a){if(a)return!x(a.children)&&
x(a.childNodes)||x(a.children)?a.children:[]}function vb(a){var c;for(c=a.parentNode;null!==c&&x(c)&&!u.isLinkElement(a);)a=c,c=a.parentNode;return a}function wb(a){return Math.round((a||new Date).getTime()/1E3)}function xb(a,c){a=String(a);return 0===a.lastIndexOf(c,0)}function ya(a,c){a=String(a);return-1!==a.indexOf(c,a.length-c.length)}function lc(a,c){a=String(a);return a.substr(0,a.length-c)}function yb(a,c){var e="(^| )(piwik[_-]"+c;if(a)for(var g=0;g<a.length;g++)e+="|"+a[g];return new RegExp(e+
")( |$)")}function ld(a,c){var e=u.getAttributeValueFromNode(a,"href");if(!e)return!1;var g=e.split("://");if(2!==g.length)return!1;e=g[0].toLowerCase();g=g[1];var h=g.indexOf("?");g=-1===h?g:g.slice(0,h);h=[];for(var p=0;p<c.length;p++){var n=c[p];md.test(n)&&h.push(n)}for(p=0;p<h.length;p++){var q=h[p].split("://");if(2!==q.length)break;n=q[0].toLowerCase();q=q[1];if(e===n&&mc(g,q))return!0}return!1}function mc(a,c){xb(c,"/")||(c="/"+c);xb(a,"/")||(a="/"+a);if("/"===c||"/*"===c||a===c)return!0;
c=String(c).toLowerCase();a=String(a).toLowerCase();if(ya(c,"*"))return(c=c.slice(0,-1))&&"/"!==c&&a!==c?0===a.indexOf(c):!0;ya(a,"/")||(a+="/");ya(c,"/")||(c+="/");return 0===a.indexOf(c)}function nc(a,c,e,g){for(var h=0;h<e.length;h++){var p=Oa(e[h]),n=Za(e[h],g);if(tb(a,p)&&mc(c,n))return!0}return!1}function oc(a,c,e){a=vb(a);if(u.hasNodeAttribute(a,"href")){var g=u.getAttributeValueFromNode(a,"href");if(g&&!$a(g,e.configTrackerUrl)){var h=hc(g),p=h.pathname||Za(g,c);g=h.hostname||Ma(h.href);var n=
g.toLowerCase();h=h.href.replace(g,n);if(!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto|tel|data|blob):/i.test(h)&&(g=a.className,c=nc(n,p,e.configHostsAlias,c),a=u.hasNodeAttribute(a,"download"),$a(h,e.configTrackerUrl)?e=0:(p=yb(e.configDownloadClasses,"download"),n=yb(e.configLinkClasses,"link"),e=new RegExp("\\.("+e.configDownloadExtensions.join("|")+")([?&#]|$)","i"),e=n.test(g)?"link":a||p.test(g)||e.test(h)?"download":c?0:"link"),e))return{type:e,href:h}}}}function Q(a,
c,e){return 0<=c&&c<=e?"&"+a+"="+c:""}function R(a,c){var e=a[c];return"number"!==typeof e?0:Math.round(e-(a.navigationStart||0))}function nd(a){var c,e={state:"loading"};if(null!==(c=navigator.userAgentData)&&void 0!==c&&c.getHighEntropyValues)navigator.userAgentData.getHighEntropyValues(od).then(function(g){e={state:"available",hints:g};a.onResolve()})["catch"](function(){e={state:"unavailable"};a.onResolve()});else e={state:"unavailable"};return{getState:function(){return e}}}function pc(a){if(!(a instanceof
Array))return{isValid:!1,error:"[enableHeartBeatTimer] - 'timers' parameter if specified, has to be array of numbers. Received: '".concat(a,"'")};if(0===a.length)return{isValid:!1,error:"[enableHeartBeatTimer] - 'timers' cannot be empty array"};for(var c=0;c<a.length;c++)if("number"!==typeof a[c])return{isValid:!1,error:"[enableHeartBeatTimer] - 'timers' array has to contain only numeric values. Received: '".concat(a,"'")};return{isValid:!0}}function pd(a){var c=!1,e=!1,g=!0,h=qc,p,n=0,q=function(){var r=
h[n];p=void 0===r?void 0:window.setTimeout(function(){if(g)a.onPing(ra.PeriodicHeartbeat);n++;q()},1E3*r)},v=function(){e&&(q(),e=!1);g||(g=!0,a.onPing(ra.PeriodicHeartbeat))},w=function(){g=!1;a.onPing(ra.BlurHeartbeat)};return{enable:function(){c=!0;window.addEventListener("focus",v);window.addEventListener("blur",w);document.hasFocus()?q():e=!0},disable:function(){e=c=!1;clearTimeout(p);p=void 0;n=0;window.removeEventListener("focus",v);window.removeEventListener("blur",w)},setTimings:function(r){var t=
pc(r);t.isValid||G(t.error);h=r},isEnabled:function(){return c}}}function qd(){var a=[[/g/g,"10"],[/h/g,"11"],[/i/g,"12"],[/j/g,"13"],[/k/g,"14"],[/l/g,"15"],[/m/g,"16"],[/n/g,"17"],[/o/g,"18"],[/p/g,"19"],[/q/g,"1a"],[/r/g,"1b"],[/s/g,"1c"],[/t/g,"1d"],[/u/g,"1e"],[/v/g,"1f"],[/w/g,"20"],[/x/g,"21"],[/y/g,"22"],[/z/g,"23"],[/_/g,"3e"],[/-/g,"3f"]],c=/^[0-9a-f]{16}$/;return function(e){if(e&&!c.test(e)){e=e.toLowerCase().substr(4,16);for(var g=0;g<a.length;g+=1)e=e.replace(a[g][0],a[g][1]);e=e.substr(0,
16)}return e}}function rd(a){return{transformIfAMPCookie:qd(),getCookieName:function(c){var e=a.getCookiesConfig();return e.cookieNamePrefix+c+"."+e.trackerSiteId+"."+e.domainHash},getCookie:function(c){return a.getCookiesConfig().cookiesDisabled?0:(c=(new RegExp("(^|;)[ ]*"+c+"=([^;]*)")).exec(a.documentAlias.cookie))?a.decodeWrapper(c[2])||0:0},setCookie:function(c,e,g){var h=a.getCookiesConfig();h.msToExpire=g?g.msToExpire||h.msToExpire:h.msToExpire;h.path=g?g.path||h.path:h.path;h.cookiesDisabled||
(e=a.encodeWrapper(e),g=h.msToExpire?new Date(Date.now()+h.msToExpire):void 0,c=c+"="+e+(g?";expires="+g.toUTCString():"")+";path="+(h.path||"/")+(h.domain?";domain="+h.domain:"")+(h.isSecure?";secure":"")+";SameSite=Lax",document.cookie=c)},deleteCookie:function(c){this.setCookie(c,"",{msToExpire:-86400})},hasCookies:function(){if(a.getCookiesConfig().cookiesDisabled)return"0";if(!x(a.navigatorAlias.cookieEnabled)){var c=this.getCookieName("_pk_testcookie");this.setCookie(c,"1");var e="1"===this.getCookie(c)?
"1":"0";this.deleteCookie(c);return e}return a.navigatorAlias.cookieEnabled?"1":"0"}}}function zb(a){function c(g,h){if(window.getComputedStyle)return document.defaultView.getComputedStyle(g,null)[h];if(g.currentStyle)return g.currentStyle[h]}function e(g,h,p,n,q,v,w){var r=g.parentNode,t;a:{for(t=g.parentNode;t;){if(t===document){t=!0;break a}t=t.parentNode}t=!1}if(!t)return!1;if(9===r.nodeType)return!0;if("0"===c(g,"opacity")||"none"===c(g,"display")||"hidden"===c(g,"visibility"))return!1;x(h)&&
x(p)&&x(n)&&x(q)&&x(v)&&x(w)||(h=g.offsetTop,q=g.offsetLeft,n=h+g.offsetHeight,p=q+g.offsetWidth,v=g.offsetWidth,w=g.offsetHeight);if(a===g&&(0===w||0===v)&&"hidden"===c(g,"overflow"))return!1;if(r){if("hidden"===c(r,"overflow")||"scroll"===c(r,"overflow"))if(q+1>r.offsetWidth+r.scrollLeft||q+v-1<r.scrollLeft||h+1>r.offsetHeight+r.scrollTop||h+w-1<r.scrollTop)return!1;g.offsetParent===r&&(q+=r.offsetLeft,h+=r.offsetTop);return e(r,h,p,n,q,v,w)}return!0}return a?e(a):!1}function rc(a){var c=function(za,
aa){return za<<aa|za>>>32-aa},e=function(za){var aa="",ea;for(ea=7;0<=ea;ea--){var Ab=za>>>4*ea&15;aa+=Ab.toString(16)}return aa},g,h=[],p=1732584193,n=4023233417,q=2562383102,v=271733878,w=3285377520,r=[];a=unescape(encodeURIComponent(a));var t=a.length;for(g=0;g<t-3;g+=4){var F=a.charCodeAt(g)<<24|a.charCodeAt(g+1)<<16|a.charCodeAt(g+2)<<8|a.charCodeAt(g+3);r.push(F)}switch(t&3){case 0:g=2147483648;break;case 1:g=a.charCodeAt(t-1)<<24|8388608;break;case 2:g=a.charCodeAt(t-2)<<24|a.charCodeAt(t-
1)<<16|32768;break;case 3:g=a.charCodeAt(t-3)<<24|a.charCodeAt(t-2)<<16|a.charCodeAt(t-1)<<8|128}for(r.push(g);14!==(r.length&15);)r.push(0);r.push(t>>>29);r.push(t<<3&4294967295);for(a=0;a<r.length;a+=16){for(g=0;16>g;g++)h[g]=r[a+g];for(g=16;79>=g;g++)h[g]=c(h[g-3]^h[g-8]^h[g-14]^h[g-16],1);F=p;t=n;var K=q;var J=v;var U=w;for(g=0;19>=g;g++){var H=c(F,5)+(t&K|~t&J)+U+h[g]+1518500249&4294967295;U=J;J=K;K=c(t,30);t=F;F=H}for(g=20;39>=g;g++)H=c(F,5)+(t^K^J)+U+h[g]+1859775393&4294967295,U=J,J=K,K=c(t,
30),t=F,F=H;for(g=40;59>=g;g++)H=c(F,5)+(t&K|t&J|K&J)+U+h[g]+2400959708&4294967295,U=J,J=K,K=c(t,30),t=F,F=H;for(g=60;79>=g;g++)H=c(F,5)+(t^K^J)+U+h[g]+3395469782&4294967295,U=J,J=K,K=c(t,30),t=F,F=H;p=p+F&4294967295;n=n+t&4294967295;q=q+K&4294967295;v=v+J&4294967295;w=w+U&4294967295}H=e(p)+e(n)+e(q)+e(v)+e(w);return H.toLowerCase()}function Aa(a,c){if("undefined"===typeof a)return!0;if("object"!==O(a)||null===a)return G("[".concat(c,"]: parameter 'options' have to be of type object or undefined. Received: ").concat(JSON.stringify(a))),
!1;if("string"===typeof a.currencyCode||"undefined"===typeof a.currencyCode)return!0;G("[".concat(c,"]: parameter 'options.currencyCode' has to be of type string or undefined Received: ").concat(JSON.stringify(a.currencyCode)));return!1}function X(a,c,e,g){if(a.addEventListener)return a.addEventListener(c,e,g),!0;if(a.attachEvent)return a.attachEvent("on"+c,e);a["on"+c]=e}function sd(a){var c={};if(!/MSIE/.test(navigator.userAgent)){if(navigator.mimeTypes&&navigator.mimeTypes.length)for(var e in Bb)if(Object.prototype.hasOwnProperty.call(Bb,
e)){var g=navigator.mimeTypes[Bb[e]];c[e]=g&&g.enabledPlugin?"1":"0"}xa(navigator.javaEnabled)&&navigator.javaEnabled()&&(c.java="1");xa(window.GearsFactory)&&(c.gears="1");c.cookie=a()}a=parseInt(screen.width,10);e=parseInt(screen.height,10);c.res=a+"x"+e;return c}function sc(a,c){c||(c=rc);return c((navigator.userAgent||"")+(navigator.platform||"")+JSON.stringify(a)).slice(0,6)}function tc(a){var c=Math.floor((new Date).getTime()/1E3);a=sc(a);return String(c)+a}function td(a,c,e,g){if(!e.crossDomainTrackingEnabled)return"";
g||(g=ub);a=g(a,e.configVisitorIdUrlParameter);if(!a)return"";a=String(a);g=/^[a-zA-Z0-9]+$/;if(16===a.length&&g.test(a))return a;if(32===a.length&&g.test(a)){a:{g=a.substr(16,32);e=e.configVisitorIdUrlParameterTimeoutInSeconds;g=String(g);c=sc(c);var h=c.length,p=g.substr(-1*h,h);if((g=parseInt(g.substr(0,g.length-h),10))&&p&&p===c){c=Math.floor((new Date).getTime()/1E3);if(0>=e){e=!0;break a}if(c>=g&&c<=g+e){e=!0;break a}}e=!1}if(e)return a.substr(0,16)}return""}function uc(a,c,e){if(a&&u.hasNodeAttribute(a,
"href")){var g=u.getAttributeValueFromNode(a,"href");g&&!$a(g,e.configTrackerUrl)&&(g=(e.crossDomainTrackingLinkDecorator||vc)(g,c+tc(e.browserFeatures),e.configVisitorIdUrlParameter),null!==g&&u.setAnyAttribute(a,"href",g))}}function vc(a,c,e){a=ic(a,e);a=String(a);c||(c="");var g=document.createElement("a");g.href=a;a=g.search.split("&");a.push(encodeURIComponent(e)+"="+encodeURIComponent(c));""===a[0]&&a.shift();g.search=a.join("&");return g.href}function ud(a,c,e){for(var g=[],h=[],p=[],n=0;n<
a.length;n++){var q=a[n];q&&(-1<Z(c,q[0])?g.push(q):-1<Z(e,q[0])?p.push(q):h.push(q))}return{toApplyFirst:g,toApplySecond:h,toApplyLast:p}}function bb(a,c,e){x(e)||(e="");try{return a[c]||e}catch(g){return e}}function Cb(a){if(!a)return!0;var c,e=!0;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&(e=!1);return e}function Ba(){for(var a=0;a<arguments.length;a+=1){var c=arguments[a];if(!Array.isArray(c)){G("[".concat(I.queueName,".push()]: expected array as argument, got ").concat(JSON.stringify(c),
". Example: ").concat(I.queueName,".push(['methodName', parameters]) or ").concat(I.queueName,".push([function(){}])"));break}for(var e=c.shift(),g=0;g<S.length;g++){var h=S[g];if(xa(e))e.apply(h,c);else if(P(e)){h[e]?h[e].apply(h,c):(h="The method '".concat(e,"' was not found in \"").concat(I.queueName,'" variable.  Please have a look at the Piwik tracker documentation'),G(h));if("addTracker"===e)break;if("setTrackerUrl"===e||"setSiteId"===e)break}}}}function cb(a,c,e,g){if(a.removeEventListener)return a.removeEventListener(c,
e,g),!0;if(a.detachEvent)return a.detachEvent("on"+c,e);a["on"+c]===e&&delete a["on"+c]}function Ca(a){"complete"===C.readyState?a():A.addEventListener?A.addEventListener("load",a):A.attachEvent&&A.attachEvent("onload",a)}function Pa(a){var c=!1;(c=C.attachEvent?"complete"===C.readyState:"loading"!==C.readyState)?a():(C.addEventListener?X(C,"DOMContentLoaded",function g(){C.removeEventListener("DOMContentLoaded",g,!1);c||(c=!0,a())}):C.attachEvent&&(C.attachEvent("onreadystatechange",function g(){"complete"===
C.readyState&&(C.detachEvent("onreadystatechange",g),c||(c=!0,a()))}),C.documentElement.doScroll&&A===A.top&&function h(){if(!c){try{C.documentElement.doScroll("left")}catch(p){setTimeout(h,0);return}c=!0;a()}}()),X(A,"load",function(){c||(c=!0,a())},!1))}function vd(){var a="";try{var c;a=(null===(c=A.top)||void 0===c?void 0:c.document.referrer)||""}catch(e){if(A.parent)try{a=A.parent.document.referrer}catch(g){a=""}}""===a&&(a=C.referrer);return a}function fa(a){return a&&String(a)===a?a.replace(/^\s+|\s+$/g,
""):a}function wc(a,c){return a&&c?a.contains?a.contains(c):a===c?!0:a.compareDocumentPosition?!!(a.compareDocumentPosition(c)&16):!1:!1}function Db(a,c){function e(b){if(!1===Eb||!0===Fb){var d=new Date;null!==Gb&&18E5<d.getTime()-Gb.getTime()||(d=H("ping=".concat(b),null,"ping"),b=b!==ra.PeriodicHeartbeat,q(d,L,null,b,b?"beacon":void 0))}}function g(b,d){var f=new Image(1,1);f.onload=function(){xa(d)&&d()};b=-1!==b.indexOf("send_image=0")?b.replace("&send_image=0","&send_image=1"):b+"&send_image=1";
f.src=ba+(0>ba.indexOf("?")?"?":"&")+b}function h(b,d,f){x(f)&&null!==f||(f=!0);try{var k=A.XMLHttpRequest?new A.XMLHttpRequest:A.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;k.open("POST",ba,!0);k.onreadystatechange=function(){4!==this.readyState||200<=this.status&&300>this.status||!f?4===this.readyState&&"function"===typeof d&&d():g(b,d)};k.setRequestHeader("Content-Type",Hb);k.send(b)}catch(l){f&&g(b,d)}}function p(b){b=(new Date).getTime()+b;if(!db||b>db)db=b}function n(b,d){var f=
(new Date).getTime();xc=f;Da&&f<Da?(f=Da-f,setTimeout(b,f),d&&p(f+50),Da+=50):(void 0===Da&&(Da=f+800),b())}function q(b,d,f,k,l){if(Ib){var z=yc.getState();if("loading"===z.state){eb.push({type:"single",request:b,delay:d,callback:f,force:k,method:l});return}"available"===z.state&&(b+=zc(z.hints))}xa(Qa)&&(b=Qa(b)||"");if(!fb&&b){var y=l||gb,D=!f&&sa.sendBeacon&&A.Blob&&65536>=b.length,N=!0;l=function(){if("beacon"===y&&D){var ca=new A.Blob([String(b)],{type:Hb});sa.sendBeacon(ba,ca)?N=!1:h(b,f)}else"POST"===
y||2E3<String(b).length?h(b,f):g(b,f);N&&p(d)};k?l():n(l,N)}}function v(b,d){var f=fb?!1:b?0<b.length:!1;if(f){if(Ib){f=yc.getState();if("loading"===f.state){eb.push({type:"bulk",requests:b,delay:d});return}if("available"===f.state)for(var k=0;k<b.length;k++)b[k]+=zc(f.hints)}if(xa(Qa)){f=[];for(k=0;k<b.length;k++){var l=Qa(b[k]);l&&f.push(l)}if(0>=f.length)return;b=f}var z='{"requests":["?'+b.join('","?')+'"]}';n(function(){h(z,null,!1);"beacon"!==gb&&p(d)},!1)}}function w(){Ac=Bc((hb||Ra)+(ib||
"/")).slice(0,4)}function r(){var b=M.getCookieName("cvar");b=M.getCookie(b);return P(b)&&b.length&&(b=JSON.parse(b),Na(b))?b:{}}function t(){Ea||(Ea=td(jb,ja,{crossDomainTrackingEnabled:Fa,configVisitorIdUrlParameter:"pk_vid",configVisitorIdUrlParameterTimeoutInSeconds:Cc},Dc));var b=wb(new Date),d=M.getCookieName("id");d=M.getCookie(d);return P(d)&&d.length?(d=d.split("."),d[0]=M.transformIfAMPCookie(d[0]),6>d.length&&(d[1]=b,d[2]=0,d[3]=b,d[4]="",d[5]=""),d.unshift("0"),Ea.length&&(d[1]=Ea),d):
d=["1",Ea.length?Ea:"0"===M.hasCookies()?"":Bc((sa.userAgent||"")+(sa.platform||"")+JSON.stringify(ja)+(new Date).getTime()+Math.random()).slice(0,16),b,0,b,"",""]}function F(){var b=t(),d=b[0],f=b[1],k=b[2],l=b[3],z=b[4],y=b[5];x(b[6])||(b[6]="");return{newVisitor:d,uuid:f,createTs:k,visitCount:l,currentVisitTs:z,lastVisitTs:y,lastEcommerceOrderTs:b[6]}}function K(b){Ga&&(x(b)||(b=F()),b=b.uuid+"."+b.createTs+"."+b.visitCount+"."+b.currentVisitTs+"."+b.lastVisitTs+"."+b.lastEcommerceOrderTs,M.setCookie(M.getCookieName("id"),
b,{msToExpire:Jb}))}function J(){var b=ta;ta=!1;var d;for(d=0;d<Kb.length;d++){var f=M.getCookieName(Kb[d]);0!==M.getCookie(f)&&M.deleteCookie(f)}ta=b}function U(b){var d=[];for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&d.push(f);var f={};d.sort();var k=d.length,l;for(l=0;l<k;l++)f[d[l]]=b[d[l]];return f}function H(b,d,f,k){var l=new Date;var z=wb(l);var y=T,D=M.getCookieName("ses"),N=M.getCookieName("cvar"),ca=M.getCookie(D),Ta=Sa||jb;ta&&J();if(fb)return"";D=F();x(k)||(k="");var ua=C.characterSet||
C.charset;ua&&"utf-8"!==ua.toLowerCase()||(ua=void 0);!ca&&(ca=Ha/1E3,!D.lastVisitTs||z-Number(D.lastVisitTs)>ca)&&(D.visitCount=Number(D.visitCount)+1,D.lastVisitTs=D.currentVisitTs,D.currentVisitTs=z);xb(b,"action_name=")&&(Eb=kb,Fb=!!D.uuid,Gb=new Date);b+="&idsite="+Ga+"&rec=1&r="+String(Math.random()).slice(2,8)+"&h="+l.getHours()+"&m="+l.getMinutes()+"&s="+l.getSeconds()+"&url="+E(ab(Ta,{discardHashTag:Ua,visitorIdUrlParameter:"pk_vid"}))+(Lb.length?"&urlref="+E(ab(Lb,{discardHashTag:Ua,visitorIdUrlParameter:"pk_vid"})):
"")+(Ia&&Ia.length?"&uid="+E(Ia):"")+(kb?"&uia=1":"")+(D.uuid?"&_id="+D.uuid:"")+"&_idts="+D.createTs+"&_idvc="+D.visitCount+(D.lastVisitTs?"&_viewts="+D.lastVisitTs:"")+(String(D.lastEcommerceOrderTs).length?"&_ects="+D.lastEcommerceOrderTs:"")+(ua?"&cs="+E(ua):"")+"&ts_n="+E(lb||Mb)+"&ts_v="+E(Nb||Ob)+(Ec?"":"&rmip=1")+(Fc&&kb?"&dda=1":"");if(!Gc)for(m in ja)Object.prototype.hasOwnProperty.call(ja,m)&&(b+="&"+m+"="+ja[m]);l=[];if(d)for(m in d)Object.prototype.hasOwnProperty.call(d,m)&&/^dimension\d+$/.test(m)&&
(z=m.replace("dimension",""),l.push(parseInt(z,10)),l.push(String(z)),b+="&"+m+"="+d[m],delete d[m]);d&&Cb(d)&&(d=null);for(m in ha)Object.prototype.hasOwnProperty.call(ha,m)&&(z=-1===Z(l,m))&&(z=RegExp("[^\x00-\u007f]"),b=(-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/"))&&null!==ha[m].match(z)?b+("&dimension"+m+"="+encodeURIComponent(ha[m])):b+("&dimension"+m+"="+ha[m]));for(m in oa)Object.prototype.hasOwnProperty.call(oa,m)&&(z=-1===Z(l,m))&&(b+="&dimension"+
encodeURIComponent(m)+"="+encodeURIComponent(oa[m]));d?b+="&data="+E(JSON.stringify(d)):pa&&(b+="&data="+E(JSON.stringify(pa)));Cb(ka)||(d=U(ka),b+="&cvar="+E(JSON.stringify(d)));Cb(Va)||(d=U(Va),b+="&e_cvar="+E(JSON.stringify(d)));if(T){b+="&_cvar="+E(JSON.stringify(T));for(m in y)Object.prototype.hasOwnProperty.call(y,m)&&(""===T[m][0]||""===T[m][1])&&delete T[m];Hc&&M.setCookie(N,JSON.stringify(T),{msToExpire:Ha})}var m=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance;
m=null!==m&&void 0!==m&&m.timing?m.timing:null!==m&&void 0!==m&&m.getEntriesByType?m.getEntriesByType("navigation")[0]:void 0;y=null;Pb&&(Qb?y=Qb:m&&m.requestStart&&m.responseEnd&&(y=m.responseEnd-m.requestStart),null!==y&&(b+="&gt_ms="+Math.max(y,0)));y=m&&m.loadEventEnd&&0!==m.loadEventEnd&&m.fetchStart&&0!==m.fetchStart;Pb&&("log"===f||"ping"===f)&&2>=mb&&!Ic&&y&&(f="",m.unloadEventStart&&0!==m.unloadEventStart&&(f+=Q("t_us",R(m,"unloadEventStart"),65535)),m.unloadEventEnd&&0!==m.unloadEventEnd&&
(f+=Q("t_ue",R(m,"unloadEventEnd"),65535)),m.redirectStart&&0!==m.redirectStart&&(f+=Q("t_rs",R(m,"redirectStart"),65535)),m.redirectEnd&&0!==m.redirectEnd&&(f+=Q("t_re",R(m,"redirectEnd"),65535)),m.secureConnectionStart&&0!==m.secureConnectionStart&&(f+=Q("t_ss",R(m,"secureConnectionStart"),65535)),m.fetchStart&&0!==m.fetchStart&&(f+=Q("t_fs",R(m,"fetchStart"),65535)),m.domainLookupStart&&0!==m.domainLookupStart&&(f+=Q("t_ds",R(m,"domainLookupStart"),65535)),m.connectStart&&0!==m.connectStart&&(f+=
Q("t_cs",R(m,"connectStart"),65535)),m.connectEnd&&0!==m.connectEnd&&(f+=Q("t_ce",R(m,"connectEnd"),65535)),m.requestStart&&0!==m.requestStart&&(f+=Q("t_qs",R(m,"requestStart"),65535)),m.responseStart&&0!==m.responseStart&&(f+=Q("t_as",R(m,"responseStart"),65535)),m.responseEnd&&0!==m.responseEnd&&(f+=Q("t_ae",R(m,"responseEnd"),65535)),m.domLoading&&0!==m.domLoading&&(f+=Q("t_dl",R(m,"domLoading"),65535)),m.domInteractive&&0!==m.domInteractive&&(f+=Q("t_di",R(m,"domInteractive"),16777215)),m.domContentLoadedEventStart&&
0!==m.domContentLoadedEventStart&&(f+=Q("t_ls",R(m,"domContentLoadedEventStart"),16777215)),m.domContentLoadedEventEnd&&0!==m.domContentLoadedEventEnd&&(f+=Q("t_le",R(m,"domContentLoadedEventEnd"),16777215)),m.domComplete&&0!==m.domComplete&&(f+=Q("t_dc",R(m,"domComplete"),16777215)),m.loadEventEnd&&0!==m.loadEventEnd&&(f+=Q("t_ee",R(m,"loadEventEnd"),16777215)),b+=f,Ic=!0);nb&&(b+="&pv_id="+nb);D.lastEcommerceOrderTs=x(k)&&String(k).length?k:D.lastEcommerceOrderTs;K(D);M.setCookie(M.getCookieName("ses"),
"*",{msToExpire:Ha});Rb.length&&(b+="&"+Rb);return b}function za(b){if(!Na(b))return G("Invalid ecommerce product: "+JSON.stringify(b)),!1;if(!Object.prototype.hasOwnProperty.call(b,"sku"))return G("Missing required SKU property in ecommerce product: "+JSON.stringify(b)+"."),!1;var d=O(b.sku);return"string"!==d&&"number"!==d?(G("Product.sku has to be of type string or number. Received: ".concat(d,". In product: ").concat(JSON.stringify(b))),!1):Object.prototype.hasOwnProperty.call(b,"customDimensions")&&
!Na(b.customDimensions)?(G('Invalid "customDimensions" property. Expected Object type, but got: '+JSON.stringify(b)+"."),!1):!0}function aa(b,d,f,k){var l=new Date,z=[];var y=""+la("");y+="&e_t="+b;null!==k&&void 0!==k&&k.currencyCode&&(y+="&cur="+k.currencyCode);if(f){b=f.orderId;k=f.grandTotal;var D=f.subTotal;var N=f.tax;var ca=f.shipping;f=f.discount;if(b){y+="&ec_id="+E(b);var Ta=wb(l)}y+="&revenue="+k;qa(D)&&(y+="&ec_st="+D);qa(N)&&(y+="&ec_tx="+N);qa(ca)&&(y+="&ec_sh="+ca);qa(f)&&(y+="&ec_dt="+
f)}if(d){for(l=0;l<d.length;l+=1){x(d[l].name)||(d[l].name="");if(!x(d[l].category))d[l].category="";else if(d[l].category instanceof Array)for(f=0;f<d[l].category.length;f+=1)P(d[l].category[f])||(d[l].category[f]="");x(d[l].price)&&0!==String(d[l].price).length||(d[l].price=0);x(d[l].quantity)&&0!==String(d[l].quantity).length||(d[l].quantity=1);x(d[l].brand)&&0!==String(d[l].brand).length||(d[l].brand="");x(d[l].variant)&&0!==String(d[l].variant).length||(d[l].variant="");x(d[l].customDimensions)||
(d[l].customDimensions={});f=z;b=f.push;a:for(k=[String(d[l].sku),String(d[l].name),d[l].category,d[l].price,d[l].quantity,d[l].brand,String(d[l].variant),d[l].customDimensions].slice();0<k.length;){D=k[k.length-1];if(!(N=""===D)&&(N=Na(D)))b:{N=void 0;for(N in D)if(Object.hasOwnProperty.call(D,N)){N=!1;break b}N=!0}if(N)k.pop();else break a}b.call(f,k)}y+="&ec_products="+E(JSON.stringify(z))}y=H(y,pa,"ecommerce",Ta);q(y,L)}function ea(b){var d,f=!0;if(b instanceof Array){for(d=0;d<b.length;d+=1)f=
f&&za(b[d]);return f}G("Invalid ecommerce products. Expected value: array of objects. Recieved: "+JSON.stringify(b)+".");return!1}function Ab(b,d){var f;if("object"!==O(b)||null===b)return G("Invalid paymentInformation. Expected object. Recieved: "+JSON.stringify(b)+"."),!1;for(f=0;f<d.length;f+=1){var k=d[f];var l=b[k];if("orderId"===k){if(!x(l)||""===String(l))return G('Invalid paymentInformation. Expected object containing "'+k+'" attribute. Recieved: '+JSON.stringify(b)+"."),!1}else if(!qa(l))return G('Invalid paymentInformation. Expected object containing [number] "'+
k+'" attribute. Recieved: '+JSON.stringify(b)+"."),!1}return!0}function Jc(b,d,f){Aa(f,"ecommerceCartUpdate")||(f=void 0);qa(d)?ea(b)&&aa("cart-update",b,{grandTotal:d},f):G('ecommerceCartUpdate requires [number] "grandTotal" parameter. Recieved: '+JSON.stringify(d)+".")}function Kc(b,d,f){Aa(f,"ecommerceOrder")||(f=void 0);ea(b)&&Ab(d,["orderId","grandTotal"])&&aa("order",b,d,f)}function Lc(){var b,d=[];if(Y){for(b in Y)if(Object.prototype.hasOwnProperty.call(Y,b)){var f={sku:Y[b][0],name:Y[b][1],
category:Y[b][2],price:Y[b][3],quantity:Y[b][4]};d.push(f)}return d}return[]}function la(b){b=(b=b||ob)&&b.text?b.text:b;if(!P(b)){var d=document.getElementsByTagName("title");d&&x(d[0])&&(b=d[0].text)}return"action_name="+E(b||"")}function wd(b,d,f){var k="",l;for(l=0;6>l;l++)k+="abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ".charAt(Math.floor(62*Math.random()));nb=k;b=H(la(b),d,"log");q(b,L,f)}function pb(b,d,f,k){if(b=B.buildInteractionRequestParams(b,d,f,k))return H("".concat(b,
"&").concat(la()),null,"contentInteraction")}function Sb(b,d){if(!b||!d)return!1;for(var f=B.findTargetNodes(b),k,l=0;l<f.length;l++)if(k=f[l],wc(k,d)&&B.shouldIgnoreInteraction(k))return!1;f=B.findTargetNodesNoDefault(b);if(!f||0===f.length)return!0;for(l=0;l<f.length;l++)if(k=f[l],wc(k,d))return!0;return!1}function Mc(b,d,f){if(b){var k=B.findParentContentNode(b);if(k&&Sb(k,b)&&(b=B.buildContentBlock(k)))return!b.target&&f&&(b.target=f),B.buildInteractionRequestParams(d,b.name,b.piece,b.target)}}
function Nc(b){if(0===va.length)return!1;var d,f;for(d=0;d<va.length;d++)if((f=va[d])&&f.name===b.name&&f.piece===b.piece&&f.target===b.target)return!0;return!1}function Oc(b){return function(d){if(b){var f=B.findParentContentNode(b),k;d&&(k=d.target||d.srcElement);k||(k=b);if(Sb(f,k)){"beacon"!==gb&&p(L);u.isLinkElement(b)&&u.hasNodeAttributeWithValue(b,"href")&&u.hasNodeAttributeWithValue(b,B.CONTENT_TARGET_ATTR)&&(d=u.getAttributeValueFromNode(b,"href"),$a(d||"",ba)||u.setAnyAttribute(b,B.CONTENT_TARGET_ATTR,
""));d=oc(b,B,{configTrackerUrl:ba,configDownloadClasses:Tb,configLinkClasses:Ub,configDownloadExtensions:ma,configHostsAlias:na});if(Ja&&d&&d.type)return d.type;if(k=B.buildContentBlock(f))if(f=k.name,d=k.piece,k=u.getAttributeValueFromNode(b,B.CONTENT_TARGET_ATTR)||k.target,f=pb("click",f,d,k))return q("".concat(f,"&").concat(la()),L),f}}}}function Pc(b){if(b&&b.length){var d,f,k;for(d=0;d<b.length;d++){var l=B.findTargetNodes(b[d]);for(k=0;k<l.length;k++)(f=l[k])&&!f.contentInteractionTrackingSetupDone&&
(f.contentInteractionTrackingSetupDone=!0,X(f,"click",Oc(f)))}}}function Qc(b,d){if(!b||!b.length)return[];var f,k;for(f=0;f<b.length;f++)Nc(b[f])?(b.splice(f,1),f--):va.push(b[f]);if(!b||!b.length)return[];Pc(d);var l=[];for(f=0;f<b.length;f++)(k=H("".concat(B.buildImpressionRequestParams(b[f].name,b[f].piece,b[f].target),"&").concat(la()),void 0,"contentImpressions"))&&l.push(k);return l}function Wa(b){var d=B.collectContent(b);return Qc(d,b)}function Vb(b){if(!b||!b.length)return[];var d;for(d=
0;d<b.length;d++)B.isNodeVisible(b[d])||(b.splice(d,1),d--);return b&&b.length?Wa(b):[]}function Rc(b,d,f){b=B.buildImpressionRequestParams(b,d,f);return H("".concat(b,"&").concat(la()),null,"contentImpression")}function Sc(b,d){if(b){var f=B.findParentContentNode(b);if(f=B.buildContentBlock(f))return d||(d="Unknown"),pb(d,f.name,f.piece,f.target)}}function Tc(b,d,f,k,l,z){if(0===fa(String(b)).length||0===fa(String(d)).length)return G("Error while logging event: Parameters `category` and `action` must not be empty or filled with whitespaces"),
!1;var y=H;b="e_c="+E(b)+"&e_a="+E(d)+(x(f)?"&e_n="+E(f):"")+(x(k)?"&e_v="+E(k):"");l=y(b+"&"+la(""),l,"event");q(l,L,z)}function Uc(b,d,f,k,l){d="".concat(la(),"&").concat(d,"=").concat(E(ab(b,{discardHashTag:Ua,visitorIdUrlParameter:"pk_vid"})));(b=Mc(l,"click",b))&&(d+="&"+b);f=H(d,f,"link");q(f,L,k,!0,"beacon")}function V(b){!Vc&&"prerendering"in C?C.prerendering?C.addEventListener("prerenderingchange",function f(){C.removeEventListener("prerenderingchange",f);b()}):b():b()}function Wb(b){if(Fa){var d=
vb(b);if(ld(d,na)){uc(d,String(F().uuid),{configVisitorIdUrlParameter:"pk_vid",configTrackerUrl:ba,browserFeatures:ja,crossDomainTrackingLinkDecorator:Xb});return}}if((d=oc(b,B,{configTrackerUrl:ba,configDownloadClasses:Tb,configLinkClasses:Ub,configDownloadExtensions:ma,configHostsAlias:na}))&&d.type)Uc(d.href,d.type,void 0,null,b);else if(Fa){b=vb(b);d=B;var f=na,k=Ra,l=u.getAttributeValueFromNode(b,"href");if(l)if(l=String(l),0!==l.indexOf("//")&&0!==l.indexOf("http://")&&0!==l.indexOf("https://"))d=
!1;else{var z=hc(l),y=z.pathname||Za(l,d);l=(z.hostname||Ma(l)).toLowerCase();d=nc(l,y,f,d)&&!tb(k,Oa(l))?!0:!1}else d=!1;d&&uc(b,String(F().uuid),{configVisitorIdUrlParameter:"pk_vid",configTrackerUrl:ba,browserFeatures:ja,crossDomainTrackingLinkDecorator:Xb})}}function Xa(b){return function(d){d=d||A.event;a:{var f=d;var k=f.which,l=O(f.button);k||"undefined"===l||(C.all&&!C.addEventListener?f.button&1?k=1:f.button&2?k=3:f.button&4&&(k=2):0===f.button||"0"===f.button?k=1:f.button&1?k=2:f.button&
2&&(k=3));switch(k){case 1:f="left";break a;case 2:f="middle";break a;case 3:f="right";break a}f=void 0}k=d.target||d.srcElement;"click"===d.type?(d=!1,b&&"middle"===f&&(d=!0),k&&!d&&Wb(k)):"mousedown"===d.type?"middle"===f&&k?(qb=f,rb=k):qb=rb=null:"mouseup"===d.type?(f===qb&&k===rb&&Wb(k),qb=rb=null):"contextmenu"===d.type&&Wb(k)}}function xd(b){function d(k){if(k.target){var l=k.target;if(l.closest)l=l.closest("a");else for(;l&&"A"!==l.tagName;)l=l.parentNode;Yb&&l&&!yb(Wc,"ignore").test(l.className)&&
Xa(b)(k)}}function f(){cb(document.body,"click",d,!1);b&&(cb(document.body,"mouseup",d,!1),cb(document.body,"mousedown",d,!1),cb(document.body,"contextmenu",d,!1))}Ja||(X(document.body,"click",d,!1),b&&(X(document.body,"mouseup",d,!1),X(document.body,"mousedown",d,!1),X(document.body,"contextmenu",d,!1)),Ja=f)}function Xc(b,d,f){function k(){l=!0}if(Ka)return!0;Ka=!0;var l=!1,z,y;Ca(function(){function D(m){setTimeout(function(){Ka&&(l=!1,f.trackVisibleContentImpressions(),D(m))},m)}function N(m){setTimeout(function(){Ka&&
(l&&(l=!1,f.trackVisibleContentImpressions()),N(m))},m)}function ca(m){if(!m)return!1;var W=m.getBoundingClientRect();if(0>=W.width||0>=W.height)return!1;W=null;if(A.getComputedStyle){var da;W=null===(da=C.defaultView)||void 0===da?void 0:da.getComputedStyle(m,null)}else!W&&m.currentStyle?W=m.currentStyle:W||(W={});return"0"===W.opacity||"none"===W.display||"hidden"===W.visibility?!1:m.parentNode instanceof Element?ca(m.parentNode):!0}function Ta(m){var W=[],da;for(da=0;da<m.length;da+=1)m[da].isIntersecting&&
ca(m[da].target)&&B.isOrWasNodeInViewport(m[da].target)&&W.push(m[da].target);m=Wa(W);v(m,L)}function ua(){if(A.IntersectionObserver){wa||(wa=new A.IntersectionObserver(Ta,{threshold:0}));var m=B.findContentNodes();for(y=0;y<m.length;y+=1)m[y].getAttribute(B.CONTENT_WATCHED_ATTR)||(wa.observe(m[y]),m[y].setAttribute(B.CONTENT_WATCHED_ATTR,"1"));return!0}return!1}(b||d&&0<d)&&ua();if(b){z=["scroll","resize"];for(y=0;y<z.length;y++)C.addEventListener?C.addEventListener(z[y],k):A.attachEvent("on"+z[y],
k);N(100)}d&&0<d&&(d=parseInt(d,10),D(d))})}function Yc(b,d,f,k){if(Zb){var l=String(b).substring(0,16E3);V(function(){var z=d+":"+f;k&&(z+=":"+k);var y=JSON.stringify({category:"JavaScript Errors",action:z,message:l});Zc&&-1!==Z($b,y)||($b.push(y),Tc("JavaScript Errors",z,l))})}}var ac=kd(C.domain,A.location.href,vd()),Ra=Oa(ac[0]),jb=ac[1],Lb=ac[2],Zb=!1,gb="beacon",Ec=!0,Fc=!1,Ib=!1,Hb="application/x-www-form-urlencoded; charset=UTF-8",ba=a||"",bc="",Rb="",Ga=c||"",kb=!1,Gc=!1,Eb=null,Fb=null,
Ia="",Ea="",cc=10,Sa,ob="",ma="7z aac apk arc arj asf asx avi azw3 bin csv deb dmg doc docx epub exe flv gif gz gzip hqx ibooks jar jpg jpeg js mobi mp2 mp3 mp4 mpg mpeg mov movie msi msp odb odf odg ods odt ogg ogv pdf phps png ppt pptx qt qtm ra ram rar rpm sea sit tar tbz tbz2 bz bz2 tgz torrent txt wav wma wmv wpd xls xlsx xml z zip".split(" "),na=[Ra],Wc=[],Tb=[],Ub=[],L=500,Gb=null,$c=!1,Ua=!1,pa,ad="_pk_",Cc=180,hb,ib,bd=!1,ta=!1,cd=!0,fb=!1,Vc=!1,Jb=339552E5,Ha=18E5,Pb=!0,Qb=0,Hc=!1,T,ka=
{},Va={},Qa,ha={},oa={},dc=200,Y={},ja={},va=[],Ka=!1,wa,Da,Ja=!1,Yb=!1,Fa=!1,Xb=vc,Dc=ub,xc=null,qb,rb,Bc=rc,Ac,nb,mb=0,Zc=!1,$b=[],Kb=["id","ses","cvar"],Mb="jstc",Ob="2.28.6",lb="",Nb="",yc=nd({onResolve:function(){for(var b=0;b<eb.length;b++){var d=eb[b];if("single"===d.type)q(d.request,d.delay,d.callback,d.force,d.method);else if("bulk"===d.type)v(d.requests,d.delay);else throw Error("[processQueue] unprocessable request type: ".concat(d));}}});try{ob=C.title}catch(b){ob=""}var La=pd({onPing:e}),
M=rd({decodeWrapper:yd,encodeWrapper:E,getCookiesConfig:function(){return{cookiesDisabled:ta,domain:hb,path:ib,isSecure:bd,trackerSiteId:Ga,cookieNamePrefix:ad,domainHash:Ac}},documentAlias:C,navigatorAlias:sa}),eb=[];this.setCustomVariableMaximumLength=function(b){dc=b};ja=sd(M.hasCookies);w();this.getQuery=function(){return u};this.getContent=function(){return B};this.buildContentImpressionRequest=Rc;this.buildContentInteractionRequest=pb;this.buildContentInteractionRequestNode=Sc;this.getContentImpressionsRequestsFromNodes=
Wa;this.getCurrentlyVisibleContentImpressionsRequestsIfNotTrackedYet=Vb;this.trackCallbackOnLoad=Ca;this.trackCallbackOnReady=Pa;this.buildContentImpressionsRequests=Qc;this.wasContentImpressionAlreadyTracked=Nc;this.appendContentInteractionToRequestIfPossible=Mc;this.setupInteractionsTracking=Pc;this.trackContentImpressionClickInteraction=Oc;this.internalIsNodeVisible=zb;this.isNodeAuthorizedToTriggerInteraction=Sb;this.getDomains=function(){return na};this.getConfigIdPageView=function(){return nb};
this.getConfigDownloadExtensions=function(){return ma};this.enableTrackOnlyVisibleContent=function(b,d){return Xc(b,d,this)};this.clearTrackedContentImpressions=function(){va=[]};this.getTrackedContentImpressions=function(){return va};this.clearEnableTrackOnlyVisibleContent=function(){Ka=!1;wa&&wa.disconnect();wa=void 0};this.disableLinkTracking=function(){"function"===typeof Ja&&Ja();Yb=Ja=!1};this.getConfigVisitorCookieTimeout=function(){return Jb};this.removeAllAsyncTrackersButFirst=function(){S=
[S[0]]};this.ping=function(){var b=H("ping=6",null,"ping");q(b,L)};this.getVisitorId=function(){return F().uuid};this.getVisitorInfo=function(){return t()};this.setTrackerUrl=function(b){ba=b};this.getTrackerUrl=function(){return ba};this.getPiwikUrl=function(){var b=this.getTrackerUrl();if(bc)b=bc;else{b=B.toAbsoluteUrl(b);var d=String(b);-1!==d.indexOf("?")&&(d=b.indexOf("?"),b=b.slice(0,d));ya(b,"ppms.php")?b=lc(b,8):ya(b,".php")&&(d=b.lastIndexOf("/"),b=b.slice(0,d+1));ya(b,"/js/")&&(b=lc(b,3))}return b};
this.addTracker=function(b,d){if(!d)throw Error("A siteId must be given to add a new tracker");x(b)&&null!==b||(b=this.getTrackerUrl());var f=new Db(b,d);S.push(f);return f};this.getSiteId=function(){return Ga};this.setSiteId=function(b){Ga=b;K();if(cd){var d=this.getTrackerUrl(),f=C.createElement("script");f.setAttribute("id","ppas_container_configuration");f.setAttribute("data-appid",b);b=f.setAttribute;var k=C.createElement("a");k.href=d;b.call(f,"data-host",k.host);C.getElementsByTagName("head")[0].appendChild(f)}};
this.setVisitorIdCookie=function(){K()};this.resetUserId=function(){Ia=""};this.setUserIsAnonymous=function(b){kb=b};this.setSessionIdStrictPrivacyMode=function(b){Gc=b};this.setTimingDataSamplingOnPageLoad=function(b){!0===b&&(b=1);!1===b&&(b=0);b=parseInt(b,10);0>b?b=0:100<b&&(b=100);cc=b};this.getTimingDataSamplingOnPageLoad=function(){return cc};this.setUserId=function(b){x(b)&&b.length&&(Ia=b)};this.getUserId=function(){return Ia};this.setCustomData=function(b,d){Na(b)?pa=b:(pa||(pa={}),pa[b]=
d)};this.getCustomData=function(){return pa};this.setCustomRequestProcessing=function(b){Qa=b};this.appendToTrackingUrl=function(b){Rb=b};this.getRequest=function(b){return H(b)};this.setCustomDimension=function(b,d){b=parseInt(b,10);0<b&&(Object.prototype.hasOwnProperty.call(oa,b)?hd("Custom dimension "+b+' was already set by "setCustomDimensionValue" method. Value set by "setCustomDimension" will be ignored.'):(x(d)||(d=""),P(d)||(d=String(d)),ha[b]=d))};this.getCustomDimension=function(b){b=parseInt(b,
10);if(0<b&&Object.prototype.hasOwnProperty.call(ha,b))return ha[b]};this.deleteCustomDimension=function(b){b=parseInt(b,10);0<b&&(delete ha[b],delete oa[b])};this.setCustomDimensionValue=function(b,d){b=parseInt(b,10);0<b&&(x(d)||(d=""),P(d)||(d=String(d)),oa[b]=d,delete ha[b])};this.getCustomDimensionValue=function(b){b=parseInt(b,10);if(0<b&&Object.prototype.hasOwnProperty.call(oa,b))return oa[b]};this.setCustomVariable=function(b,d,f,k){x(k)||(k="visit");x(d)&&(x(f)||(f=""),0<b&&(d=P(d)?d:String(d),
f=P(f)?f:String(f),d=[d.slice(0,dc),f.slice(0,dc)],"visit"===k||2===k?(T||(T=r()),T[b]=d):"page"===k||3===k?ka[b]=d:"event"===k&&(Va[b]=d)))};this.getCustomVariable=function(b,d){x(d)||(d="visit");if("page"===d||3===d)var f=ka[b];else if("event"===d)f=Va[b];else if("visit"===d||2===d)T||(T=r()),f=T[b];return!x(f)||f&&""===f[0]?!1:f};this.deleteCustomVariable=function(b,d){this.getCustomVariable(b,d)&&this.setCustomVariable(b,"","",d)};this.deleteCustomVariables=function(b){if("page"===b||3===b)ka=
{};else if("event"===b)Va={};else if("visit"===b||2===b)T={}};this.storeCustomVariablesInCookie=function(){Hc=!0};this.setLinkTrackingTimer=function(b){L=b};this.getLinkTrackingTimer=function(){return L};this.setDownloadExtensions=function(b){P(b)&&(b=b.split("|"));ma=b};this.addDownloadExtensions=function(b){var d;P(b)&&(b=b.split("|"));for(d=0;d<b.length;d++)ma.push(b[d])};this.removeDownloadExtensions=function(b){var d,f=[];P(b)&&(b=b.split("|"));for(d=0;d<ma.length;d++)-1===Z(b,ma[d])&&f.push(ma[d]);
ma=f};this.setDomains=function(b){na=P(b)?[b]:b;b=!1;for(var d=0;d<na.length;d++){var f=String(na[d]);if(tb(Ra,Oa(f))){b=!0;break}if((f=Za(f,B))&&"/"!==f&&"/*"!==f){b=!0;break}}b||na.push(Ra)};this.enableCrossDomainLinking=function(){Fa=!0};this.disableCrossDomainLinking=function(){Fa=!1};this.isCrossDomainLinkingEnabled=function(){return Fa};this.customCrossDomainLinkDecorator=function(b){Xb=b};this.customCrossDomainLinkVisitorIdGetter=function(b){Dc=b};this.setCrossDomainLinkingTimeout=function(b){Cc=
b};this.getCrossDomainLinkingUrlParameter=function(){var b=F().uuid;return E("pk_vid")+"="+E(String(b)+tc(ja))};this.setIgnoreClasses=function(b){Wc=P(b)?[b]:b};this.setRequestMethod=function(b){gb=b||"beacon"};this.setRequestContentType=function(b){Hb=b||"application/x-www-form-urlencoded; charset=UTF-8"};this.setReferrerUrl=function(b){Lb=b};this.setCustomUrl=function(b){if("string"!==typeof b)G("[setCustomUrl]: url must be a string, got: ".concat(JSON.stringify(b)));else{var d=jb,f=Ua;jc(b)?Sa=
b:"/"===b.slice(0,1)?Sa=jc(d)+"://"+Ma(d)+b:(d=ab(d,{discardHashTag:f,visitorIdUrlParameter:"pk_vid"}),f=d.indexOf("?"),0<=f&&(d=d.slice(0,f)),f=d.lastIndexOf("/"),f!==d.length-1&&(d=d.slice(0,f+1)),Sa=d+b)}};this.getCurrentUrl=function(){return Sa||jb};this.setDocumentTitle=function(b){ob=b};this.setAPIUrl=function(b){bc=b};this.setDownloadClasses=function(b){Tb=P(b)?[b]:b};this.setLinkClasses=function(b){Ub=P(b)?[b]:b};this.discardHashTag=function(b){Ua=b};this.setCookieNamePrefix=function(b){ad=
b;T=r()};this.setCookieDomain=function(b){hb=Oa(b);w()};this.getCookieDomain=function(){return hb};this.hasCookies=function(){return"1"===M.hasCookies()};this.setSessionCookie=function(b,d,f){if(!b)throw Error("Missing cookie name");x(f)||(f=Ha);Kb.push(b);M.setCookie(M.getCookieName(b),d,{msToExpire:f})};this.getCookie=function(b){b=M.getCookie(M.getCookieName(b));return 0===b?null:b};this.setCookiePath=function(b){ib=b;w()};this.getCookiePath=function(){return ib};this.setVisitorCookieTimeout=function(b){Jb=
1E3*b};this.setSessionCookieTimeout=function(b){Ha=1E3*b};this.getSessionCookieTimeout=function(){return Ha};this.setReferralCookieTimeout=function(){};this.setSecureCookie=function(b){bd=b};this.disableCookies=function(){ta=!0;Ga&&J()};this.enableCookies=function(){ta=!1};this.deleteCookies=function(){J()};this.setSiteInspectorSetup=function(b){cd=b};this.setDoNotTrack=function(b){var d=sa.doNotTrack||sa.msDoNotTrack;(fb=b&&("yes"===d||"1"===d))&&this.disableCookies()};this.addListener=function(b,
d){var f=d;"undefined"===O(f)&&(f=!0);X(b,"click",Xa(!!f),!1);f&&(X(b,"mouseup",Xa(f),!1),X(b,"mousedown",Xa(f),!1),X(b,"contextmenu",Xa(f),!1))};this.enableLinkTracking=function(b){this.disableLinkTracking();"undefined"===typeof b&&(b=!0);Yb=!0;V(function(){Pa(function(){xd(b)})})};this.enableJSErrorTracking=function(b){x(b)||(b=!0);if(!Zb){Zb=!0;Zc=b;var d=A.onerror;A.onerror=function(f,k,l,z,y){Yc(f,k,l,z);return d?d(f,k,l,z,y):!1}}};this.disablePerformanceTracking=function(){Pb=!1};this.setGenerationTimeMs=
function(b){Qb=parseInt(b,10)};this.enableHeartBeatTimer=function(b){if(b){var d=pc(b);if(!d.isValid){G(d.error);return}}else b=qc;La.setTimings(b);$c=!0;null!==xc&&La.enable()};this.disableHeartBeatTimer=function(){La.disable()};this.killFrame=function(){A.location!==A.top.location&&(A.top.location=A.location)};this.redirectFile=function(b){"file:"===A.location.protocol&&(A.location=b)};this.setCountPreRendered=function(b){Vc=b};this.trackGoal=function(b,d,f,k){Aa(k,"trackGoal")||(k=void 0);V(function(){var l=
k;l=H("idgoal="+b+(d?"&revenue="+d:"")+"&"+la("")+(null!==l&&void 0!==l&&l.currencyCode?"&cur="+l.currencyCode:""),f,"goal");q(l,L)})};this.trackLink=function(b,d,f,k){V(function(){Uc(b,d,f,k)})};this.getNumTrackedPageViews=function(){return mb};this.trackHeartBeat=function(b){var d=!C.hasFocus||C.hasFocus();La.isEnabled()&&d&&(!1===Eb||!0===Fb)&&(d=ra.PeriodicHeartbeat,null!==b&&void 0!==b&&b.lastHeartbeat&&(d=ra.LastHeartbeat),null!==b&&void 0!==b&&b.blurHeartbeat&&(d=ra.BlurHeartbeat),e(d))};this.trackPageView=
function(b,d,f){va=[];$b=[];V(function(){mb++;wd(b,d,f);$c&&!La.isEnabled()&&La.enable();1>=mb&&cc>=Math.floor(100*Math.random()+1)&&Ca(function(){setTimeout(function(){var k=H("ping=5",null,"ping");q(k,L)},0)})})};this.trackAllContentImpressions=function(){V(function(){Pa(function(){var b=B.findContentNodes();b=Wa(b);v(b,L)})})};this.trackVisibleContentImpressions=function(b,d){x(b)||(b=!0);x(d)||(d=750);Xc(b,d,this);wa||V(function(){Ca(function(){var f=B.findContentNodes();f=Vb(f);v(f,L)})})};this.trackContentImpression=
function(b,d,f){b=fa(b);d=fa(d||"Unknown");f=fa(f||"");b&&V(function(){var k=Rc(b,d,f);q(k,L)})};this.trackContentImpressionsWithinNode=function(b){b&&V(function(){Ka?Ca(function(){var d=B.findContentNodesWithinNode(b);d=Vb(d);v(d,L)}):Pa(function(){var d=B.findContentNodesWithinNode(b);d=Wa(d);v(d,L)})})};this.trackContentInteraction=function(b,d,f,k){b=fa(b);d=fa(d);f=fa(f||"Unknown");k=fa(k||"");b&&d&&V(function(){var l=pb(b,d,f,k);l&&q(l,L)})};this.trackContentInteractionNode=function(b,d){b&&
V(function(){var f=Sc(b,d);f&&q(f,L)})};this.logAllContentBlocksOnPage=function(){var b=B.findContentNodes();b=B.collectContent(b);console.log(b)};this.trackEvent=function(b,d,f,k,l,z){x(k)&&!qa(k)&&G("[trackEvent]: Value parameter must be a number or number representation. Received: ".concat(JSON.stringify(k)));V(function(){Tc(b,d,f,k,l,z)})};this.trackSiteSearch=function(b,d,f,k){V(function(){var l=H("search="+E(b)+(d?"&search_cats="+E(JSON.stringify(P(d)?[d]:d)):"")+(x(f)?"&search_count="+f:""),
k,"sitesearch");q(l,L)})};this.setEcommerceView=function(b,d,f,k){x(f)&&f.length?f instanceof Array&&(f=JSON.stringify(f)):f="";ka[5]=["_pkc",f];x(k)&&String(k).length&&(ka[2]=["_pkp",k]);if(x(b)&&b.length||x(d)&&d.length)x(b)&&b.length&&(ka[3]=["_pks",b]),x(d)&&d.length||(d=""),ka[4]=["_pkn",d]};this.getEcommerceItems=function(){return JSON.parse(JSON.stringify(Y))};this.addEcommerceItem=function(b,d,f,k,l){b.length&&(Y[b]=[b,d,f,k,l])};this.removeEcommerceItem=function(b){b.length&&delete Y[b]};
this.clearEcommerceCart=function(){Y={}};this.trackEcommerceOrder=function(b,d,f,k,l,z){String(b).length&&x(d)&&(Kc(Lc(),{orderId:b,grandTotal:d,subTotal:f,tax:k,shipping:l,discount:z}),Y={})};this.trackEcommerceCartUpdate=function(b){Jc(Lc(),b)};this.ecommerceProductDetailView=function(b,d){Aa(d,"ecommerceProductDetailView")||(d=void 0);ea(b)&&aa("product-detail-view",b,void 0,d)};this.ecommerceAddToCart=function(b,d){Aa(d,"ecommerceAddToCart")||(d=void 0);ea(b)&&aa("add-to-cart",b,void 0,d)};this.ecommerceRemoveFromCart=
function(b,d){Aa(d,"ecommerceRemoveFromCart")||(d=void 0);ea(b)&&aa("remove-from-cart",b,void 0,d)};this.ecommerceCartUpdate=Jc;this.ecommerceOrder=Kc;this.trackError=function(b){if(b){try{var d=zd.parse(b);var f=d[0]}catch(k){}Yc(bb(b,"message"),bb(f,"fileName"),bb(f,"lineNumber"),bb(f,"columnNumber"))}};this.trackRequest=function(b,d,f,k){V(function(){var l=H(b,d,k);q(l,L,f)})};this.deanonymizeUser=function(){this.setUserIsAnonymous(!1);var b=H("ping=4",null,"ping");q(b,L)};this.getTrackingSource=
function(){return[Mb,Ob]};this.setTrackingSource=function(b,d){Mb=String(b);void 0!==d&&(Ob=String(d))};this.setTrackingSourceProvider=function(b,d){"string"!==typeof b?G("[setTrackingSourceProvider]: 'provider' has to be of type string"):"string"!==typeof d?G("[setTrackingSourceProvider]: 'providerVersion' has to be of type string"):(lb=b,Nb=d)};this.getTrackingSourceProvider=function(){if(lb)return[lb,Nb]};this.setIpTracking=function(b){Ec=b};this.setDeviceDataAnonymization=function(b){"boolean"!==
typeof b?G("setDeviceDataAnonymization: The value for device data anonymization must be a boolean"):Fc=b};this.setEnableClientHints=function(b){"boolean"!==typeof b?G("[setEnableClientHints]: The value for enabling client hints must be a boolean"):Ib=b};ec.trigger("TrackerSetup",[this])}function Ad(a,c){var e={},g,h;for(g=0;g<c.length;g++){var p=c[g];e[p]=1;for(h=0;h<a.length;h++)if(a[h]&&a[h][0]){var n=a[h][0];p===n&&(Ba(a[h]),delete a[h],1<e[n]&&"addTracker"!==n&&"enableLinkTracking"!==n&&"setSecureCookie"!==
n&&"enableCrossDomainLinking"!==n&&G("The method "+n+' is registered more than once in "'+I.queueName+'" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation'),e[n]++)}}Ba(["setVisitorIdCookie"])}function dd(a,c){var e=new Db(a,c);S.push(e);var g=window[I.queueName].splice(0,window[I.queueName].length),h=ud(g,ed,Bd),p=h.toApplySecond;g=h.toApplyLast;Ad(h.toApplyFirst,ed);for(h=0;h<p.length;h++)Ba(p[h]);p=window[I.queueName];for(h=0;h<p.length;h++)Ba(p[h]);
for(p=0;p<g.length;p++)Ba(g[p]);if("number"===typeof window[I.queueName].length){var n={push:Ba},q=Date.now();window[I.queueName]=n;var v=setInterval(function(){6E4<Date.now()-q?clearInterval(v):window[I.queueName]!==n&&(G("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/."),
clearInterval(v))},1E3)}else G("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/.");return e}function Cd(a,c,e,g){function h(n){try{if(window["piwik_"+n])return window["piwik_"+n]}catch(q){}}var p=window.Piwik.getTracker(e,c);p.setDocumentTitle(a);p.setCustomData(g);(a=h("tracker_pause"))&&
p.setLinkTrackingTimer(a);(a=h("download_extensions"))&&p.setDownloadExtensions(a);(a=h("hosts_alias"))&&p.setDomains(a);(a=h("ignore_classes"))&&p.setIgnoreClasses(a);p.setTimingDataSamplingOnPageLoad(0);p.trackPageView();h("install_tracker")&&(window.piwik_track=function(n,q,v,w){p.setSiteId(q);p.setTrackerUrl(v);p.trackLink(n,w)},p.enableLinkTracking())}var I={queueName:"_paq",objectName:"Piwik"},sb={exports:{}},Ya={exports:{}},jd=Ya.exports,gc,Dd=sb.exports,fd,zd=function(a){return a&&a.__esModule&&
Object.prototype.hasOwnProperty.call(a,"default")?a["default"]:a}(function(){if(fd)return sb.exports;fd=1;(function(a,c){(function(e,g){a.exports=g(id())})(Dd,function(e){var g=/(^|@)\S+:\d+/,h=/^\s*at .*(\S+:\d+|\(native\))/m,p=/^(eval@)?(\[native code])?$/;return{parse:function(n){if("undefined"!==typeof n.stacktrace||"undefined"!==typeof n["opera#sourceloc"])return this.parseOpera(n);if(n.stack&&n.stack.match(h))return this.parseV8OrIE(n);if(n.stack)return this.parseFFOrSafari(n);throw Error("Cannot parse given Error object");
},extractLocation:function(n){if(-1===n.indexOf(":"))return[n];n=/(.+?)(?::(\d+))?(?::(\d+))?$/.exec(n.replace(/[()]/g,""));return[n[1],n[2]||void 0,n[3]||void 0]},parseV8OrIE:function(n){return n.stack.split("\n").filter(function(q){return!!q.match(h)},this).map(function(q){-1<q.indexOf("(eval ")&&(q=q.replace(/eval code/g,"eval").replace(/(\(eval at [^()]*)|(,.*$)/g,""));var v=q.replace(/^\s+/,"").replace(/\(eval code/g,"(").replace(/^.*?\s+/,""),w=v.match(/ (\(.+\)$)/);v=w?v.replace(w[0],""):v;
var r=this.extractLocation(w?w[1]:v);v=w&&v||void 0;w=-1<["eval","<anonymous>"].indexOf(r[0])?void 0:r[0];return new e({functionName:v,fileName:w,lineNumber:r[1],columnNumber:r[2],source:q})},this)},parseFFOrSafari:function(n){return n.stack.split("\n").filter(function(q){return!q.match(p)},this).map(function(q){-1<q.indexOf(" > eval")&&(q=q.replace(/ line (\d+)(?: > eval line \d+)* > eval:\d+:\d+/g,":$1"));if(-1===q.indexOf("@")&&-1===q.indexOf(":"))return new e({functionName:q});var v=/((.*".+"[^@]*)?[^@]*)(?:@)/,
w=q.match(v);w=w&&w[1]?w[1]:void 0;v=this.extractLocation(q.replace(v,""));return new e({functionName:w,fileName:v[0],lineNumber:v[1],columnNumber:v[2],source:q})},this)},parseOpera:function(n){return!n.stacktrace||-1<n.message.indexOf("\n")&&n.message.split("\n").length>n.stacktrace.split("\n").length?this.parseOpera9(n):n.stack?this.parseOpera11(n):this.parseOpera10(n)},parseOpera9:function(n){var q=/Line (\d+).*script (?:in )?(\S+)/i;n=n.message.split("\n");for(var v=[],w=2,r=n.length;w<r;w+=2){var t=
q.exec(n[w]);t&&v.push(new e({fileName:t[2],lineNumber:t[1],source:n[w]}))}return v},parseOpera10:function(n){var q=/Line (\d+).*script (?:in )?(\S+)(?:: In function (\S+))?$/i;n=n.stacktrace.split("\n");for(var v=[],w=0,r=n.length;w<r;w+=2){var t=q.exec(n[w]);t&&v.push(new e({functionName:t[3]||void 0,fileName:t[2],lineNumber:t[1],source:n[w]}))}return v},parseOpera11:function(n){return n.stack.split("\n").filter(function(q){return!!q.match(g)&&!q.match(/^Error created at/)},this).map(function(q){var v=
q.split("@"),w=this.extractLocation(v.pop()),r=v.shift()||"";v=r.replace(/<anonymous function(: (\w+))?>/,"$2").replace(/\([^)]*\)/g,"")||void 0;var t;r.match(/\(([^)]*)\)/)&&(t=r.replace(/^[^(]+\(([^)]*)\)$/,"$1"));t=void 0===t||"[arguments not available]"===t?void 0:t.split(",");return new e({functionName:v,args:t,fileName:w[0],lineNumber:w[1],columnNumber:w[2],source:q})},this)}}})})(sb);return sb.exports}()),u={htmlCollectionToArray:function(a){var c=[],e;if(!a||!a.length)return c;for(e=0;e<a.length;e++)c.push(a[e]);
return c},find:function(a){if(!document.querySelectorAll||!a)return[];a=document.querySelectorAll(a);return u.htmlCollectionToArray(a)},findMultiple:function(a){if(!a||!a.length)return[];var c,e=[];for(c=0;c<a.length;c++){var g=u.find(a[c]);e=e.concat(g)}return e=u.makeNodesUnique(e)},findNodesByTagName:function(a,c){if(!a||!c||!a.getElementsByTagName)return[];var e=a.getElementsByTagName(c);return u.htmlCollectionToArray(e)},makeNodesUnique:function(a){var c=[].concat(a);a.sort(function(n,q){if(n===
q)return 0;var v=Z(c,n),w=Z(c,q);return v===w?0:v>w?-1:1});if(1>=a.length)return a;var e=0,g=0,h=[],p;for(p=a[e++];p;)p===a[e]&&(g=h.push(e)),p=a[e++]||null;for(;g--;)a.splice(h[g],1);return a},getAttributeValueFromNode:function(a,c){if(u.hasNodeAttribute(a,c)){if(a&&a.getAttribute)return a.getAttribute(c);if(a&&a.attributes&&"undefined"!==O(a.attributes[c])){if(a.attributes[c].value)return a.attributes[c].value;if(a.attributes[c].nodeValue)return a.attributes[c].nodeValue;var e,g=a.attributes;if(g){for(e=
0;e<g.length;e++)if(g[e].nodeName===c)return g[e].nodeValue;return null}}}},hasNodeAttributeWithValue:function(a,c){return!!u.getAttributeValueFromNode(a,c)},hasNodeAttribute:function(a,c){return a&&a.hasAttribute?a.hasAttribute(c):a&&a.attributes?"undefined"!==O(a.attributes[c]):!1},hasNodeCssClass:function(a,c){if(a&&c&&a.className){var e="string"===typeof a.className?a.className.split(" "):[];if(-1!==Z(e,c))return!0}return!1},findNodesHavingAttribute:function(a,c,e){e||(e=[]);if(!a||!c)return e;
a=kc(a);if(!a)return e;var g;for(g=0;g<a.length;g++){var h=a[g];u.hasNodeAttribute(h,c)&&e.push(h);e=u.findNodesHavingAttribute(h,c,e)}return e},findFirstNodeHavingAttribute:function(a,c){if(a&&c){if(u.hasNodeAttribute(a,c))return a;var e=u.findNodesHavingAttribute(a,c);if(e&&e.length)return e[0]}},findFirstNodeHavingAttributeWithValue:function(a,c){if(a&&c){if(u.hasNodeAttributeWithValue(a,c))return a;var e=u.findNodesHavingAttribute(a,c);if(e&&e.length){var g;for(g=0;g<e.length;g++)if(u.getAttributeValueFromNode(e[g],
c))return e[g]}}},findNodesHavingCssClass:function(a,c,e){e||(e=[]);if(!a||!c)return e;if(a.getElementsByClassName)return c=a.getElementsByClassName(c),u.htmlCollectionToArray(c);a=kc(a);if(!a)return[];var g;for(g=0;g<a.length;g++){var h=a[g];u.hasNodeCssClass(h,c)&&e.push(h);e=u.findNodesHavingCssClass(h,c,e)}return e},findFirstNodeHavingClass:function(a,c){if(a&&c){if(u.hasNodeCssClass(a,c))return a;var e=u.findNodesHavingCssClass(a,c);if(e&&e.length)return e[0]}},isLinkElement:function(a){if(!a)return!1;
a=String(a.nodeName).toLowerCase();return-1!==Z(["a","area"],a)},setAnyAttribute:function(a,c,e){a&&c&&(a.setAttribute?a.setAttribute(c,e):a[c]=e)}},md=/^[a-z]+:\/\/.+$/i,gd={model:"ch_m",brands:"ch_b",platform:"ch_p",platformVersion:"ch_pv",fullVersionList:"ch_fvl"},od=Object.keys(gd),zc=function(a){if("object"!==O(a))return"";var c="",e;for(e in a){var g=gd[e],h=a[e];if(g&&h){g="&".concat(g,"=");var p=g.concat;h?(h="object"===O(h)?JSON.stringify(h):h,h=window.encodeURIComponent(h)):h="";c+=p.call(g,
h)}}return c},qc=[15,30,60,120,240,480,960,1800],ra={PeriodicHeartbeat:1,LastHeartbeat:2,BlurHeartbeat:3},Bb=Object.freeze({pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",java:"application/x-java-vm",gears:"application/x-googlegears",ag:"application/x-silverlight"}),db,ia={},C=document,sa=navigator,A=window,Ic=!1,E=A.encodeURIComponent,yd=A.decodeURIComponent,S=[],fc=[],B=
{CONTENT_ATTR:"data-track-content",CONTENT_CLASS:"piwikTrackContent",CONTENT_NAME_ATTR:"data-content-name",CONTENT_PIECE_ATTR:"data-content-piece",CONTENT_PIECE_CLASS:"piwikContentPiece",CONTENT_TARGET_ATTR:"data-content-target",CONTENT_TARGET_CLASS:"piwikContentTarget",CONTENT_IGNOREINTERACTION_ATTR:"data-content-ignoreinteraction",CONTENT_IGNOREINTERACTION_CLASS:"piwikContentIgnoreInteraction",CONTENT_WATCHED_ATTR:"data-content-watched",location:void 0,findContentNodes:function(){return u.findMultiple(["."+
this.CONTENT_CLASS,"["+this.CONTENT_ATTR+"]"])},findContentNodesWithinNode:function(a){if(!a)return[];var c=u.findNodesHavingCssClass(a,this.CONTENT_CLASS),e=u.findNodesHavingAttribute(a,this.CONTENT_ATTR);if(e&&e.length){var g;for(g=0;g<e.length;g++)c.push(e[g])}u.hasNodeAttribute(a,this.CONTENT_ATTR)?c.push(a):u.hasNodeCssClass(a,this.CONTENT_CLASS)&&c.push(a);return c=u.makeNodesUnique(c)},findParentContentNode:function(a){if(a)for(var c=0;a&&a!==C&&a.parentNode;){if(u.hasNodeAttribute(a,this.CONTENT_ATTR)||
u.hasNodeCssClass(a,this.CONTENT_CLASS))return a;a=a.parentNode;if(1E3<c)break;c++}},findPieceNode:function(a){var c;(c=u.findFirstNodeHavingAttribute(a,this.CONTENT_PIECE_ATTR))||(c=u.findFirstNodeHavingClass(a,this.CONTENT_PIECE_CLASS));return c?c:a},findTargetNodeNoDefault:function(a){if(a){var c=u.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_TARGET_ATTR);if(c||(c=u.findFirstNodeHavingAttribute(a,this.CONTENT_TARGET_ATTR))||(c=u.findFirstNodeHavingClass(a,this.CONTENT_TARGET_CLASS)))return c}},
findTargetNode:function(a){var c=this.findTargetNodeNoDefault(a);return c?c:a},findTargetNodesNoDefault:function(a){if(a){var c=u.findNodesHavingAttribute(a,this.CONTENT_TARGET_ATTR);if(c&&0<c.length||(c=u.findNodesHavingCssClass(a,this.CONTENT_TARGET_CLASS))&&0<c.length)return c}},findTargetNodes:function(a){var c=B.findTargetNodesNoDefault(a);return c&&0<c.length?c:[a]},findContentName:function(a){if(a){var c=u.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_NAME_ATTR);if(c)return u.getAttributeValueFromNode(c,
this.CONTENT_NAME_ATTR);if(c=this.findContentPiece(a))return this.removeDomainIfIsInLink(c);if(u.hasNodeAttributeWithValue(a,"title"))return u.getAttributeValueFromNode(a,"title");c=this.findPieceNode(a);if(u.hasNodeAttributeWithValue(c,"title"))return u.getAttributeValueFromNode(c,"title");a=this.findTargetNode(a);if(u.hasNodeAttributeWithValue(a,"title"))return u.getAttributeValueFromNode(a,"title")}},findContentPiece:function(a){if(a){var c=u.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_PIECE_ATTR);
if(c)return u.getAttributeValueFromNode(c,this.CONTENT_PIECE_ATTR);a=this.findPieceNode(a);if(a=this.findMediaUrlInNode(a))return this.toAbsoluteUrl(a)}},findContentTarget:function(a){if(a){var c=this.findTargetNode(a);if(u.hasNodeAttributeWithValue(c,this.CONTENT_TARGET_ATTR))return u.getAttributeValueFromNode(c,this.CONTENT_TARGET_ATTR);if(u.hasNodeAttributeWithValue(c,"href"))return a=u.getAttributeValueFromNode(c,"href"),this.toAbsoluteUrl(a);a=this.findPieceNode(a);if(u.hasNodeAttributeWithValue(a,
"href"))return a=u.getAttributeValueFromNode(a,"href"),this.toAbsoluteUrl(a)}},isSameDomain:function(a){if(!a||!a.indexOf)return!1;if(0===a.indexOf(this.getLocation().origin))return!0;a=a.indexOf(this.getLocation().host);return 8>=a&&0<=a?!0:!1},removeDomainIfIsInLink:function(a){a&&a.search&&-1!==a.search(/^https?:\/\/[^/]+/)&&this.isSameDomain(a)&&((a=a.replace(/^.*\/\/[^/]+/,""))||(a="/"));return a},findMediaUrlInNode:function(a){if(a){var c=a.nodeName.toLowerCase();if(-1!==Z(["img","embed","video",
"audio"],c)&&u.findFirstNodeHavingAttributeWithValue(a,"src"))return a=u.findFirstNodeHavingAttributeWithValue(a,"src"),u.getAttributeValueFromNode(a,"src");if("object"===c&&u.hasNodeAttributeWithValue(a,"data"))return u.getAttributeValueFromNode(a,"data");if("object"===c){if((c=u.findNodesByTagName(a,"param"))&&c.length){var e;for(e=0;e<c.length;e++)if("movie"===u.getAttributeValueFromNode(c[e],"name")&&u.hasNodeAttributeWithValue(c[e],"value"))return u.getAttributeValueFromNode(c[e],"value")}if((a=
u.findNodesByTagName(a,"embed"))&&a.length)return this.findMediaUrlInNode(a[0])}}},trim:function(a){return fa(a)},isOrWasNodeInViewport:function(a){if(!a||!a.getBoundingClientRect||1!==a.nodeType)return!0;var c=a.getBoundingClientRect(),e=C.documentElement||{},g=0>c.top;g&&a.offsetTop&&(g=0<a.offsetTop+c.height);a=e.clientWidth;A.innerWidth&&a>A.innerWidth&&(a=A.innerWidth);e=e.clientHeight;A.innerHeight&&e>A.innerHeight&&(e=A.innerHeight);return(0<c.bottom||g)&&0<c.right&&c.left<a&&(c.top<e||g)},
isNodeVisible:function(a){var c=zb(a);a=this.isOrWasNodeInViewport(a);return c&&a},buildInteractionRequestParams:function(a,c,e,g){var h="";a&&(h+="c_i="+E(a));c&&(h&&(h+="&"),h+="c_n="+E(c));e&&(h&&(h+="&"),h+="c_p="+E(e));g&&(h&&(h+="&"),h+="c_t="+E(g));return h},buildImpressionRequestParams:function(a,c,e){a="c_n="+E(a)+"&c_p="+E(c);e&&(a+="&c_t="+E(e));return a},buildContentBlock:function(a){if(a){var c=this.findContentName(a),e=this.findContentPiece(a);a=this.findContentTarget(a);c=c?this.trim(c):
"Unknown";e=e?this.trim(e):"Unknown";a=a?this.trim(a):"";return{name:c,piece:e,target:a}}},collectContent:function(a){if(!a||!a.length)return[];var c=[],e;for(e=0;e<a.length;e++){var g=this.buildContentBlock(a[e]);x(g)&&c.push(g)}return c},setLocation:function(a){this.location=a},getLocation:function(){var a=this.location||A.location;a.origin||(a.origin=a.protocol+"//"+a.hostname+(a.port?":"+a.port:""));return a},toAbsoluteUrl:function(a){var c;return a&&String(a)===a||""===a?""===a?this.getLocation().href:
-1!==a.search(/^\/\//)?this.getLocation().protocol+a:-1!==a.search(/:\/\//)?a:0===a.indexOf("#")||0===a.indexOf("?")?this.getLocation().origin+this.getLocation().pathname+a:0===a.search("^[a-zA-Z]{2,11}:")?a:-1!==a.search(/^\//)?this.getLocation().origin+a:this.getLocation().origin+((null===(c=this.getLocation().pathname)||void 0===c||null===(c=c.match(/(.*\/)/))||void 0===c?void 0:c[0])||"")+a:a},isUrlToCurrentDomain:function(a){a=this.toAbsoluteUrl(a);if(!a)return!1;var c=this.getLocation().origin;
return c===a?!0:0===String(a).indexOf(c)?":"===String(a).substr(c.length,1)?!1:!0:!1},setHrefAttribute:function(a,c){a&&c&&u.setAnyAttribute(a,"href",c)},shouldIgnoreInteraction:function(a){var c=u.hasNodeAttribute(a,this.CONTENT_IGNOREINTERACTION_ATTR);a=u.hasNodeCssClass(a,this.CONTENT_IGNOREINTERACTION_CLASS);return c||a}},ed="addTracker setTrackingSourceProvider disableCookies enableCookies setSessionIdStrictPrivacyMode setTrackerUrl setAPIUrl enableCrossDomainLinking setCrossDomainLinkingTimeout customCrossDomainLinkDecorator customCrossDomainLinkVisitorIdGetter setSecureCookie setCookiePath setCookieDomain setDomains setUserId setSiteInspectorSetup setSiteId enableLinkTracking setCustomVariableMaximumLength setDeviceDataAnonymization setEnableClientHints setUserIsAnonymous".split(" "),
Bd=["trackError"];X(A,"beforeunload",function(){for(var a=S,c=db,e=0;e<a.length;e+=1)a[e].trackHeartBeat({lastHeartbeat:!0});for(a=0;a<fc.length;a+=1)fc[a].trackHeartBeat({lastHeartbeat:!0});if(c){do a=new Date;while(a.getTime()<c)}},!1);var ec={initialized:!1,JSON:JSON,DOM:{addEventListener:function(a,c,e,g){"undefined"===O(g)&&(g=!1);X(a,c,e,g)},onLoad:Ca,onReady:Pa,isNodeVisible:zb,isOrWasNodeVisible:B.isNodeVisible},on:function(a,c){ia[a]||(ia[a]=[]);ia[a].push(c)},off:function(a,c){if(ia[a]){var e=
0;for(e;e<ia[a].length;e++)ia[a][e]===c&&ia[a].splice(e,1)}},trigger:function(a,c,e){if(ia[a]){var g=0;for(g;g<ia[a].length;g++)ia[a][g].apply(e||A,c)}},getTracker:function(a,c){x(c)||(c=this.getAsyncTracker().getSiteId());x(a)||(a=this.getAsyncTracker().getTrackerUrl());var e=new Db(a,c);fc.push(e);return e},getAsyncTrackers:function(){return S},addTracker:function(a,c){return S.length?S[0].addTracker(a,c):dd(a,c)},getAsyncTracker:function(a,c){if(S&&S.length&&S[0])var e=S[0];else return dd(a,c);
if(!c&&!a)return e;x(c)&&null!==c||!e||(c=e.getSiteId());x(a)&&null!==a||!e||(a=e.getTrackerUrl());var g=0;for(g;g<S.length;g++)if((e=S[g])&&String(e.getSiteId())===String(c)&&e.getTrackerUrl()===a)return e}};"function"===typeof define&&define.amd&&define("piwik",[],function(){return ec});var Ed=ec;"object"!==O(window[I.queueName])&&(window[I.queueName]=[]);"object"!==O(window[I.objectName])&&(window[I.objectName]=Ed);(function(){window[I.objectName].getAsyncTrackers().length?G("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/."):
("object"!==O(window[I.queueName])||"undefined"===O(window[I.queueName].length)?0:window[I.queueName].length)?window[I.objectName].addTracker():window[I.queueName]={push:function(a){G(I.queueName+".push() was used but Piwik tracker was not initialized before the ppms.js file was loaded. Make sure to configure the tracker via _paq.push before loading ppms.js. Alternatively, you can create a tracker via Piwik.addTracker() manually and then use _paq.push but it may not fully work as tracker methods may not be executed in the correct order.",
a)}};window[I.objectName].trigger("PiwikInitialized",[]);window[I.objectName].initialized=!0})();"undefined"===O(window.AnalyticsTracker)&&(window.AnalyticsTracker=window[I.objectName]);"function"!==typeof window[I.objectName].piwik_log&&(window.piwik_log=Cd)})()
//# sourceMappingURL=ppms.js.map

